name: SuperDarkCore
version: 0.5.0
description: Shared code between all SuperDark plugins
api-version: 1.21

authors: [EncryptedData, onnesh]

main: net.superdark.minecraft.plugins.SuperDarkCore.SuperDarkCorePlugin

permissions:
  superdark.admin:
    description: Gives admin permssion to user.
    default: op

commands:
  sdadmin:
    usage: /sdadmin
    permission: superdark.admin
  test:
    aliases:
      - t
      - t1
    usage: /test
    permission: superdark.admin
  rtp:
    aliases:
      - randomteleport
    usage: /rtp (range)
    permission: superdark.admin
